GET http://localhost:5000

###

GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/auth

{
	"x-auth-token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVkNjY1ODRlNWRlOWQzOGI4NjQ3NzYyIn0sImlhdCI6MTU5MTEwODk5NiwiZXhwIjoxNTkxNDY4OTk2fQ.TPUjAgrxoLnfFaWLcNyvfHYBIjq8bFPp5C35uMB-n7E"
}

###

GET http://localhost:5000/api/profile

###

GET http://localhost:5000/api/posts